{
 "title": "order status monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "order-used-memory-status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "app_used_memory{app=\"order\"}/(1024*1024)"
    }
   ]
  },
  {
   "title": "order-request-502-growth-rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_requests_total{app=\"order\",status=\"502\"}[5m])"
    }
   ]
  },
  {
   "title": "order-requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{app=\"order\",status=\"200\"}",
     "legendFormat": "200"
    },
    {
     "expr": "sum(http_requests_total{app=\"order\"})",
     "legendFormat": "200+502"
    }
   ]
  }
 ]
}