route:
    receiver: 'slack'

receivers: 
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            api_url: "https://hooks.slack.com/services/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"
            channel: "#test"
            text: "{{ .CommonAnnotations.description }}"
            title: "{{ .CommonAnnotations.summary }}"

